In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [11]:
adult = pd.read_csv('adult.csv', names = ['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
                                          'marital-status', 'occupation',
                'relationship', 'race', 'gender', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'target'])

In [15]:
adult.head()

age          workclass  fnlwgt   education  educational-num  \
0   39          State-gov   77516   Bachelors               13   
1   50   Self-emp-not-inc   83311   Bachelors               13   
2   38            Private  215646     HS-grad                9   
3   53            Private  234721        11th                7   
4   28            Private  338409   Bachelors               13   

        marital-status          occupation    relationship    race   gender  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  target  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [16]:
adult.tail()

age      workclass  fnlwgt    education  educational-num  \
32556   27        Private  257302   Assoc-acdm               12   
32557   40        Private  154374      HS-grad                9   
32558   58        Private  151910      HS-grad                9   
32559   22        Private  201490      HS-grad                9   
32560   52   Self-emp-inc  287927      HS-grad                9   

            marital-status          occupation relationship    race   gender  \
32556   Married-civ-spouse        Tech-support         Wife   White   Female   
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32558              Widowed        Adm-clerical    Unmarried   White   Female   
32559        Never-married        Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female   

       capital-gain  capital-loss  hours-per-week  native-country  target  
32556             0             0              38   United-States   <=50K  
32557             0             0              40   United-States    >50K  
32558             0             0              40   United-States   <=50K  
32559             0             0              20   United-States   <=50K  
32560         15024             0              40   United-States    >50K

In [13]:
adult.shape

(32561, 15)

In [18]:
adult.describe()

age        fnlwgt  educational-num  capital-gain  \
count  32561.000000  3.256100e+04     32561.000000  32561.000000   
mean      38.581647  1.897784e+05        10.080679   1077.648844   
std       13.640433  1.055500e+05         2.572720   7385.292085   
min       17.000000  1.228500e+04         1.000000      0.000000   
25%       28.000000  1.178270e+05         9.000000      0.000000   
50%       37.000000  1.783560e+05        10.000000      0.000000   
75%       48.000000  2.370510e+05        12.000000      0.000000   
max       90.000000  1.484705e+06        16.000000  99999.000000   

       capital-loss  hours-per-week  
count  32561.000000    32561.000000  
mean      87.303830       40.437456  
std      402.960219       12.347429  
min        0.000000        1.000000  
25%        0.000000       40.000000  
50%        0.000000       40.000000  
75%        0.000000       45.000000  
max     4356.000000       99.000000

In [21]:
adult.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
target             0
dtype: int64

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [24]:
for col in adult.columns:
    if adult[col].dtypes == 'object':
        adult[col] = le.fit_transform(adult[col])

In [25]:
adult.head()

age  workclass  fnlwgt  education  educational-num  marital-status  \
0   39          7   77516          9               13               4   
1   50          6   83311          9               13               2   
2   38          4  215646         11                9               0   
3   53          4  234721          1                7               2   
4   28          4  338409          9               13               2   

   occupation  relationship  race  gender  capital-gain  capital-loss  \
0           1             1     4       1          2174             0   
1           4             0     4       1             0             0   
2           6             1     4       1             0             0   
3           6             0     2       1             0             0   
4          10             5     2       0             0             0   

   hours-per-week  native-country  target  
0              40              39       0  
1              13              39       0  
2              40              39       0  
3              40              39       0  
4              40               5       0

In [63]:
x = adult[['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']]

In [64]:
y = adult.target

In [66]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 42)

In [67]:
model = []

In [73]:
model.append(("LR", LogisticRegression()))
model.append(("LDA", LinearDiscriminantAnalysis()))
model.append(("KNN", KNeighborsClassifier()))
model.append(("CART", DecisionTreeClassifier()))
model.append(("NB", GaussianNB()))

In [74]:
result = []

In [75]:
names = []

In [78]:
from sklearn import model_selection

In [90]:
for name, models in model:
    kfold = model_selection.KFold(n_splits = 10, random_state = 7)
    cv_result = model_selection.cross_val_score(models, x_train, y_train, cv = kfold, scoring = 'accuracy')
    result.append(cv_result)
    names.append(name)
    msg = "%s, %f(%f)"%(name, cv_result.mean().cv_result.std())
    print(msg)

C:\Users\Prashant\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:297: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
C:\Users\Prashant\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Prashant\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED L

AttributeError: 'numpy.float64' object has no attribute 'cv_result'

In [102]:
from sklearn.metrics import confusion_matrix

# Training & Predicting using Logistic Regression()

In [103]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier()

In [104]:
y_pred = classifier_knn.predict(x_test)

In [105]:
y_pred

array([0, 0, 0, ..., 0, 0, 1])

In [97]:
confusion_matrix(y_test, y_pred)

array([[6858,  597],
       [1567,  747]], dtype=int64)

In [106]:
7605/9769

0.7784829562903061

# Training & Predicting using KNN Classifier

In [107]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier()

In [108]:
y_pred = classifier_knn.predict(x_test)

In [109]:
confusion_matrix(y_test, y_pred)

array([[6858,  597],
       [1567,  747]], dtype=int64)

In [111]:
(6858+747)/(6858+747+597+1567)

0.7784829562903061

# Training & Predicting using Naive Bayes


In [112]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train, y_train)

GaussianNB()

In [113]:
y_pred = classifier_nb.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 1])

In [114]:
confusion_matrix(y_test, y_pred)

array([[7078,  377],
       [1587,  727]], dtype=int64)

In [115]:
(7078+727)/(7078+727+377+1587)

0.7989558808475791

# Training & Predicting using Decision Tree Classifier

In [117]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion = 'entropy')
classifier_dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [118]:
y_pred = classifier_dt.predict(x_test)
y_pred

array([0, 1, 1, ..., 0, 1, 1])

In [119]:
confusion_matrix(y_test, y_pred)

array([[6471,  984],
       [ 871, 1443]], dtype=int64)

In [120]:
(6471+1443)/(6471+1443+987+871)

0.8098649201801065

# Training & Predicting using Random Forest

In [121]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators = 3, criterion='entropy')
classifier_rf.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [122]:
y_pred = classifier_rf.predict(x_test)
y_pred

array([0, 1, 1, ..., 0, 1, 1])

In [123]:
confusion_matrix(y_test, y_pred)

array([[6674,  781],
       [ 844, 1470]], dtype=int64)

In [124]:
(6674+1470)/(6674+1470+781+844)

0.8336574879721568

# End of EDA